main method public only
type does not have to be public apparently to call a main method

improved runTests scripts

diff --git a/bin/runTests b/bin/runTests
--- a/bin/runTests
+++ b/bin/runTests
@@ -74,122 +74,119 @@ if [ -d "$RUN_DIR" ] ; then
    if [ -f "$RUN_DIR/failed" ] ; then
       echo "Passed: `wc -l < $RUN_DIR/passed | xargs` Errors: `wc -l < $RUN_DIR/failed | xargs` of total: `wc -l < $RUN_DIR/testsRun | xargs`"
       echo "Failed tests ---- :"
-      cat "$RUN_DIR/failed"
-
-      acceptYN=""
-      while [[ ! $acceptYN =~ [aynsAYNS] ]] ; 
+      failIdx=0
+      testArray=($(cat ${RUN_DIR}/failed))
+      for testName in "${testArray[@]}"
       do
-         read -p "Accept all/none/some changes? [ans] " acceptYN
-         if [[ ! $acceptYN =~ [aynsAYNS] ]] ; then
-             echo "Invalid: $acceptYN - enter a or y for all, n for none or s for some"
-         fi
+          echo "${failIdx}: ${testName}"
+          let failIdx=${failIdx}+1
       done
 
-      if [[ $acceptYN =~ [yaYA] ]] ; then 
-         testArray=($(cat ${RUN_DIR}/failed))
+      testAns=""
+      while [[ ! $testAns =~ [qQ] ]] ; 
+      do
+         read -p "Enter: [h] for help or [qalovd][<i>]: " testAns
+         if [[ $testAns =~ [lL] ]] ; then
+            newTestArray=($(cat ${RUN_DIR}/failed))
+            echo "Failed tests:"
+            failIdx=0
+            for testName in "${newTestArray[@]}"
+            do
+                echo "${failIdx}: ${testName}"
+                let failIdx=${failIdx}+1
+            done
+         elif [[ $testAns =~ [oOaAdDvV][0-9]+ ]] ; then
+            testIndex=${testAns:1}
+            if [[ $testIndex -gt -1 ]] && [[ $testIndex -lt ${#testArray[@]} ]] ; then
+               testName=${testArray[${testIndex}]}
+               TEST_DIR="$RUN_DIR/$testName"
+               VALID_DIR="$VALID_RESULTS/$testName"
+               if [[ $testAns =~ [oO][0-9]+ ]] ; then
+                  echo "---- ${testName} new cmd:"
+                  cat "$TEST_DIR/cmd"
+                  echo "---- new output:"
+                  cat "$TEST_DIR/outf" 
+                  echo "----------"
+               elif [[ $testAns =~ [vV][0-9]+ ]] ; then
+                  echo "---- ${testName} valid cmd:"
+                  cat "$VALID_DIR/cmd"
+                  echo "---- valid output:"
+                  cat "$VALID_DIR/out" 
+                  echo "----------"
+               elif [[ $testAns =~ [dD][0-9]+ ]] ; then
+                  if ! diff "$TEST_DIR/cmd" "$VALID_DIR/cmd" > /dev/null ; then 
+                      echo "---- cmd changed < valid > new:"
+                      diff "$VALID_DIR/cmd" "$TEST_DIR/cmd"|| true
+                  fi
+                  if ! diff "$TEST_DIR/status" "$VALID_DIR/status" > /dev/null ; then 
+                      echo "---- exit status changed < valid > new:"
+                      diff "$VALID_DIR/status" "$TEST_DIR/status" || true
+                  fi
+                  if ! diff "$VALID_DIR/out" "$TEST_DIR/outf" > /dev/null ; then 
+                      echo "---- output changed < valid > new:"
+                      diff "$VALID_DIR/out" "$TEST_DIR/outf"|| true
+                  fi
+                  if [[ -d "$TEST_DIR/pages" ]] || [[ -d "$VALID_DIR/pages" ]] ; then
+                     if ! diff -r "$VALID_DIR/pages" "$TEST_DIR/pagesf" > /dev/null ; then 
+                         echo "---- pages changed < valid > new:"
+                         diff -r "$VALID_DIR/pages" "$TEST_DIR/pagesf" || true
+                     fi
+                  fi
+                  echo "----------"
+               elif [[ $testAns =~ [aA][0-9]+ ]] ; then
+                  echo "Accepting new results for $testName"
+                  cp "$TEST_DIR/outf" "$VALID_DIR/out"
+                  cp "$TEST_DIR/status" "$VALID_DIR/status"
+                  cp "$TEST_DIR/cmd" "$VALID_DIR/cmd"
+                  if [ -d "$TEST_DIR/pages" ] ; then
+                     if [ -d "$VALID_DIR/pages" ] ; then
+                        rm -rf "$VALID_DIR/pages" 
+                     fi
+                     cp -r "$TEST_DIR/pagesf" "$VALID_DIR/pages"
+                     echo "Updated valid pages dir $VALID_DIR/pages"
+                  elif [ -d "$VALID_DIR/pages" ] ; then
+                     rm -rf "$VALID_DIR/pages" 
+                     echo "Warning: removed old valid pages dir $VALID_DIR/pages"
+                  fi
+                  sed "s/^${testName}\$/+${testName}/" < ${RUN_DIR}/failed > ${RUN_DIR}/new-failed
+                  mv ${RUN_DIR}/new-failed ${RUN_DIR}/failed
+               fi
+            else 
+               echo "Test index outside of the range 0-${#testArray[@]}"
+            fi
+         elif [[ $testAns =~ [aA] ]] ; then
 
-         for testName in "${testArray[@]}"
-         do
-            echo "Updating valid file for $testName"
-            TEST_DIR="$RUN_DIR/$testName"
-            VALID_DIR="$VALID_RESULTS/$testName"
-            cp "$TEST_DIR/outf" "$VALID_DIR/out"
-            cp "$TEST_DIR/status" "$VALID_DIR/status"
-            cp "$TEST_DIR/cmd" "$VALID_DIR/cmd"
-            if [ -d "$TEST_DIR/pages" ] ; then
-               if [ -d "$VALID_DIR/pages" ] ; then
+            for testName in "${testArray[@]}"
+            do
+               echo "Updating valid file for $testName"
+               TEST_DIR="$RUN_DIR/$testName"
+               VALID_DIR="$VALID_RESULTS/$testName"
+               cp "$TEST_DIR/outf" "$VALID_DIR/out"
+               cp "$TEST_DIR/status" "$VALID_DIR/status"
+               cp "$TEST_DIR/cmd" "$VALID_DIR/cmd"
+               if [ -d "$TEST_DIR/pages" ] ; then
+                  if [ -d "$VALID_DIR/pages" ] ; then
+                     rm -rf "$VALID_DIR/pages" 
+                  fi
+                  cp -r "$TEST_DIR/pagesf" "$VALID_DIR/pages"
+                  echo "Updated valid pages dir $VALID_DIR/pages"
+               else 
                   rm -rf "$VALID_DIR/pages" 
                fi
-               cp -r "$TEST_DIR/pagesf" "$VALID_DIR/pages"
-               echo "Updated valid pages dir $VALID_DIR/pages"
-            else 
-               rm -rf "$VALID_DIR/pages" 
-            fi
-         done
-      elif [[ $acceptYN =~ [sS] ]] ; then
-         testArray=($(cat ${RUN_DIR}/failed))
-
-         failIdx=0
-         echo "Failed tests:"
-         for testName in "${testArray[@]}"
-         do
-             echo "${failIdx}: ${testName}"
-             let failIdx=${failIdx}+1
-         done
-         testAns=""
-         while [[ ! $testAns =~ [qQ] ]] ; 
-         do
-            read -p "Enter [q] to quit or [sad]<testIndex> with s: show, a: accept, d: diff, l:list: " testAns
-            if [[ $testAns =~ [sSaAdD][0-9]+ ]] ; then
-               testIndex=${testAns:1}
-               if [[ $testIndex -gt -1 ]] && [[ $testIndex -lt ${#testArray[@]} ]] ; then
-                  testName=${testArray[${testIndex}]}
-                  TEST_DIR="$RUN_DIR/$testName"
-                  VALID_DIR="$VALID_RESULTS/$testName"
-                  if [[ $testAns =~ [sS][0-9]+ ]] ; then
-                     echo "---- ${testName} cmd:"
-                     cat "$TEST_DIR/cmd"
-                     echo "---- output:"
-                     cat "$TEST_DIR/outf" 
-                     echo "----------"
-                  elif [[ $testAns =~ [dD][0-9]+ ]] ; then
-                     if ! diff "$TEST_DIR/cmd" "$VALID_DIR/cmd" > /dev/null ; then 
-                         echo "---- cmd changed < valid > new:"
-                         diff "$VALID_DIR/cmd" "$TEST_DIR/cmd"|| true
-                     fi
-                     if ! diff "$TEST_DIR/status" "$VALID_DIR/status" > /dev/null ; then 
-                         echo "---- exit status changed < valid > new:"
-                         diff "$VALID_DIR/status" "$TEST_DIR/status" || true
-                     fi
-                     if ! diff "$VALID_DIR/out" "$TEST_DIR/outf" > /dev/null ; then 
-                         echo "---- output changed < valid > new:"
-                         diff "$VALID_DIR/out" "$TEST_DIR/outf"|| true
-                     fi
-                     if [[ -d "$TEST_DIR/pages" ]] || [[ -d "$VALID_DIR/pages" ]] ; then
-                        if ! diff -r "$VALID_DIR/pages" "$TEST_DIR/pagesf" > /dev/null ; then 
-                            echo "---- pages changed < valid > new:"
-                            diff -r "$VALID_DIR/pages" "$TEST_DIR/pagesf" || true
-                        fi
-                     fi
-                     echo "----------"
-                  elif [[ $testAns =~ [aA][0-9]+ ]] ; then
-                     echo "Accepting new results for $testName"
-                     cp "$TEST_DIR/outf" "$VALID_DIR/out"
-                     cp "$TEST_DIR/status" "$VALID_DIR/status"
-                     cp "$TEST_DIR/cmd" "$VALID_DIR/cmd"
-                     if [ -d "$TEST_DIR/pages" ] ; then
-                        if [ -d "$VALID_DIR/pages" ] ; then
-                           rm -rf "$VALID_DIR/pages" 
-                        fi
-                        cp -r "$TEST_DIR/pagesf" "$VALID_DIR/pages"
-                        echo "Updated valid pages dir $VALID_DIR/pages"
-                     elif [ -d "$VALID_DIR/pages" ] ; then
-                        rm -rf "$VALID_DIR/pages" 
-                        echo "Warning: removed old valid pages dir $VALID_DIR/pages"
-                     fi
-                     sed "s/${testName}/+${testName}/" < ${RUN_DIR}/failed > /tmp/new-failed
-                     mv /tmp/new-failed ${RUN_DIR}/failed
-                  fi
-               else 
-                  echo "Test index outside of the range 0-${#testArray[@]}"
-               fi
-            elif [[ $testAns =~ [lL] ]] ; then
-               echo "Failed tests:"
-               for testName in "${testArray[@]}"
-               do
-                   echo "${failIdx}: ${testName}"
-                   let failIdx=${failIdx}+1
-               done
-            elif [[ ! $testAns =~ [qQ] ]] ; then
-                echo "Invalid: $testAns - enter s<n> to show, a<n> to accept, d<n> to diff, q to quit"
-            fi
-         done
-      fi
+            done
+         elif [[ $testAns =~ [hH] ]] ; then
+            echo "Enter: [q] - quit, [a][<i>] - accept all or one by index"
+            echo "       [l] - list, [o]<i> - show test output"
+            echo "       [v]<i> show valid output, [d]<i> show diffs"
+         elif [[ ! $testAns =~ [qQ] ]] ; then
+             echo "Invalid: $testAns - enter [aqlsd][<testIndex>]"
+         fi
+      done
    elif [ -f "$RUN_DIR/passed" ] ; then 
-       echo "Passed: `wc -l < $RUN_DIR/passed | xargs`" 
+       echo "All `wc -l < $RUN_DIR/passed | xargs` verified tests passed" 
    fi
    if [ -f "$RUN_DIR/ignored" ] ; then
-       echo "Ignored:"
+       echo "Ignored these tests from: ${RUN_DIR}/ignored"
        cat $RUN_DIR/ignored
    fi
 else
