Test script changes for browser scripting
- create temp layer when running test scripts so we can put the script in a dynamic layer
and not affect the code we're testing

- new options.testScriptName and options.testMode to make it easier to run the test scripts
for a project and customize the test script.

- command line now has an inputFileName we can add rather than always reading from stdin

- execAsync for launching chrome

- fixed injection for using .schtml as suffix for newly created types in command line

- more synchronization around the command line

- support for server method calls to the client

diff --git a/bin/testEnv b/bin/testEnv
--- a/bin/testEnv
+++ b/bin/testEnv
@@ -65,6 +65,22 @@ do
        STOP_ON_ERROR=1
        shift
        ;;
+       -h|--help)
+       echo "StrataCode test help: run test scripts or individual tests using: "
+       echo "runTests [test-options] [list of script names to run from SCRIPT_DIR: $SCRIPT_DIR - defaults to contents of 'allScripts']"
+       echo " - or - "
+       echo "runTest <test-name> [test-options] testCommand testArgs"
+       echo ""
+       echo "--- Test Options:"
+       echo "  -p/--prompt - interactive mode"
+       echo "  -v/--verbose - verbose output and errors enabled"
+       echo "  ---ignore - ignore errors"
+       echo "  --tag - name of directory to store results in: $RESULTS_DIR"
+       echo "  -q/--quiet - No error or test output displayed"
+       echo "  -s/--stop - Stop on error"
+       echo "  --results-dir <dir> - change results dir from default: $RESULTS_DIR"
+       exit 1
+       ;;
        *)
        # All test options must be in front - Rest of the args go for the list of scripts or the arguments to the command we are running
        while [[ $# -gt 0 ]]
